### ISSUE TITLE
Lens Calibration for NIKKOR Z 14-30mm f/4 S and NIKKOR Z 50mm f/1.8 S

### ISSUE THREAD

**Issue by tasnad** [lensfun/lensfun#1020]
Hi,
I performed an as careful as possible Distortyion, TCA and Vignetting calibration for the two lenses with calibrate.py.
I attached the [results](https://github.com/lensfun/lensfun/files/3745976/lenses.zip) (lenses.txt ans xml).
Please let me know if I should provide the RAWs and Hugin projects as well. 
A quick check with some files suggest that the calibration was successful.

**Comment by uchrisu** [comment]
If you would upload your RAW files, I will test your calibration file on these RAWs and add them to master if they work well in my test. If you use the standard upload, please leave a note here if you have done the upload

**Comment by tasnad** [comment]
Sure, here they are: https://github.com/lensfun/lensfun/issues/1028
I hope they are ok. When taking the pictures, I overlooked that my horizontal lines did not go over the whole image for all angles, but I researched a bit and found that hugin should be fine with it, as long as I do the line detection by hand. So I also included the hugin projects.

**Comment by uchrisu** [comment]
Distortion and TCA look okay, although the building might not be perfect it seems so be good enough. The resulting lines have only a few pixels variation in distortion, I think thats okay.

 However, the Vignetting results look a bit weird. The reason is a non uniform light distribution. On the bottom right there is some spot, thus, the resulting histogram after correction shifted some values from larger radii to a values brighter than the center. That should not happen. 
From the histogram I could not be distinguished whether it is really overcompensation. 
However, deeper inspection on single pixel values shows that only the bright spots are too bright and the "standard" corners might only be a little bit under-compensated but only to a very small level.

For that reason, and since we do not have better data, I would suggest to take the profile as it is. The values are quite reasonable. 

If nobody complains within the next two weeks, I would add it to the master database.

**Comment by tasnad** [comment]
Yes, I should and will redo the vignetting (maybe also the TCA).
The corners are usually too bright after vignetting compensation, so I'd vote for not merging this in this state, except if it's not too much work to change it afterwards?

**Comment by junkyardsparkle** [comment]
> I'd vote for not merging this in this state, except if it's not too much work to change it afterwards?

One thing to keep in mind about this: while it's easy enough to make changes to profiles already in the database, it's something that should be avoided as much as possible. As soon as something is committed here, it has the potential to end up in the workflow of anyone who updates their local database. In the case of non-destructive editors like darktable, etc this means that changing a profile later can silently impact edits already made to images. It probably won't cause the end of the world, but it's a reason to try to get things right before merging. :-)

**Comment by uchrisu** [comment]
Okay, since the contributor @tasnad wants to deliver a new profile with new data, it will we be the best to wait for that: I agree. 
Thank you for the additional work @tasnad .

**Comment by tasnad** [comment]
I finally found some time today, the upload is at https://github.com/lensfun/lensfun/issues/1187
I also included the hugin project files with the control points.

Distortion looks very well now, vignetting also seems to be ok.

**Comment by rkowalke** [comment]
A few days ago MR #1198 with all calibrations for the 50mm lens was merged into master.

**Comment by dailyherold** [comment]
Any way to help get the 14-30mm calibration data in? I might be renting the lens next month, but wasn't sure if we already had all we needed already?

**Comment by Sturmflut** [comment]
I merged the NIKKOR Z 14-30mm f/4 S lens.
