### ISSUE TITLE
Lens calibration service should support Canon CR3 files

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#1139]
Unfortunately, Canon introduced yet another RAW file format (instead of supporting DNG) called “CR3”.  Neither exiv2 nor dcraw can handle this format, yet we rely on these tools in our calibration tool chain.  This issue covers discussion and progress on this problem.

CR3 files cause trouble at two stages: The images upload, where the RAWs are analysed using exiv2, and the calibration itself, where `calibrate.py` creates TIFFs using dcraw.

I *think* Exiftool can deal with CR3. A possible solution could be to use Exiftool for CR3, and to use some other RAW processor (maybe Darktable’s command line interface) for creating the TIFFs.

**Comment by dheijl** [comment]
LibRaw supports Canon CR3 files, as does exiftool.

**Comment by tuxfanx** [comment]
it doesn't depend on lensfun --> closed

**Comment by mdjnewman** [comment]
(I don't want to revive a Zombie, so shout out if I should open a new issue to discuss this)

I came here looking to report that `calibrate.py` doesn't work on CR3 images out of a Canon EOS R10.

I think this issue is referring to CR3 support for https://wilson.bronger.org/calibration, or in the `calibrate.py` script when run locally.

`LibRaw` and `exiftool` were mentioned as they're potential replacements for `exiv2` and `dcraw`, as used by `calibrate.py`.

`dcraw` can be replaced with `dcraw_emu` in my environment (like @dheijl mentioned). I'm looking at replacing `exiv2` still.

**Comment by mdjnewman** [comment]
Ah, `exiv2 ` support for CR3s was added a while ago (https://github.com/Exiv2/exiv2/issues/236) 🎉

**Comment by sarunasb** [comment]
[e03a11d](https://github.com/lensfun/lensfun/commit/e03a11d3bf9718a009c524ea8a8d22329145a7f0) enables support for CR3.
