### ISSUE TITLE
Vignetting corrections for Sigma 60-600mm F4.5-6.3 DG OS HSM | S with 1.4x extender on Canon EF-S mount

### ISSUE THREAD

**Issue by tomato42** [lensfun/lensfun#1239]
Shot with Sigma 1.4x teleconverter TC-1401 on Canon 7D Mark II

[Sigma60-600+1.4x.zip](https://github.com/lensfun/lensfun/files/5133051/Sigma60-600%2B1.4x.zip)

**Comment by tuxfanx** [comment]
Unfortunately I don't have any raw images for a test. Maybe [you can provide some here](https://wilson.bronger.org/calibration).

**Comment by tomato42** [comment]
Uploaded in #2007 

BTW, I didn't upload of the pictures here (nor in #1238), as the documentation I found on the webpage didn't state that should be done if you calculate the corrections yourself. You might want to change that...

**Comment by tuxfanx** [comment]
Thanks for your answer.
Personally, because of some bad experiences, I only merge correction data that I was able to test myself. It may be that others handle it differently. Unfortunately I have no possibility to change the websites.
Your uploaded pictures contain no indications of a 1.4x teleconverter in the Exif data and the vignetting is corrected well with the data from #1238. Were the pictures really taken with a teleconverter? If that's the case, is there really any advantage in including the lens profile in the db?

**Comment by tomato42** [comment]
Facepalm, I was confused because I had just vignetting pictures and was looking both for the regular and with TC, ended up copying the ones without TC... Sorry about that.

Uploaded ones with teleconverter to https://github.com/lensfun/lensfun/issues/2008

**Comment by tuxfanx** [comment]
Thanks for the pictures!
Unfortunately could not get automatic detection working. So you have to choose the lens manually.

**Comment by tomato42** [comment]
weird, rawtherapee does show me that the teleconverter is on... oh well
