### ISSUE TITLE
Request to add Viltrox AF 23/1.4 XF lens profile

### ISSUE THREAD

**Issue by bachrocks** [lensfun/lensfun#1242]
Dear lensfun community
Viltrox have released a number of lenses. Particularly for Fujifilm users, this is really great news and there are many Fujians who bought these lenses as the offering of third party AF lenses for Fujifilm-X is very limited.
Viltrox provide lens profiles on their website (http://www.viltrox.com/en/index.php?m=index&a=content&cid=119) for Lightroom and Photoshop. Is it possible to convert these files for use with lensfun?
Maybe try AF 23/1.4 XF for a start.
Other lenses like the AF 33/1.4 XF are equally interesting.
If a conversion is not possible, I'd offer to contact Viltrox and try to ask for suitable profiles. You just need to tell me what exactly you need.
Kind regards

**Comment by karlstevens** [comment]
Looks like they're just LCP files;  you can import them with lensfun-convert-lcp.

**Comment by bachrocks** [comment]
@karlstevens Many thanks for your prompt reply! I see this will work with Linux.

Like many others, I use darktable for Windows. Preferred solution would be IMHO if the lensfun community were so kind to add the Viltrox lens profiles to the lensfun database; with the next darktable version, the profiles should be ready for use.

As an alternative, I can imagine that Windows users "just" need to manually add the information buried in the LCP files to one of the xml files (maybe to the 'misc.xml'?) darktable uses for lens correction. I am not sure whether my hypothesis is correct and how exactly to proceed. I welcome any helpful recommendations.

Cheers,

**Comment by karlstevens** [comment]
@bachrocks  The documentation from lensfun-convert-lcp has this to say:

"Note however, that Adobe files tend to undercorrect distortion and vignetting. In particular, vignetting is corrected only partially. Moreover, since recent Adobe products do not correct TCA based on LCP files anymore, TCA coverage is bad for newer lenses. And last but not least, automatic lens detection is much more reliable with genuine Lensfun datasets. In Lensfun's official database, no profiles using “acm” models are accepted. Thus, instead of using LCP profiles, please consider [uploading RAW images suitable for calibration](http://wilson.bronger.org/calibration). This way, you do not only benefit from increased quality, but you also help others with the same lens models by providing freely available data."

**Comment by bachrocks** [comment]
@karlstevens OK thank you! I will try to deliver the required raws asap. Already started with the vignetting images according to the guidelines. Limitation for the distortion images is the small number of modern buildings with straight lines in the area where we live but I'll do my very best.
Cheers,

**Comment by bachrocks** [comment]
@karlstevens 
Today I took calibration photos and uploaded them.
See #1248 
Kind regards,
Martin
