### ISSUE TITLE
Calibration data for NIKKOR Z 20mm f/1.8 S

### ISSUE THREAD

**Issue by pierre885** [lensfun/lensfun#1298]
Please add the attached lens data to the lensfun data base.
[lensfun_calibration-Nikkor-20mm.tar.gz](https://github.com/lensfun/lensfun/files/5506677/lensfun_calibration-Nikkor-20mm.tar.gz)

Note: the 10 MB vignetting.pdf file was removed from the archive.

**Comment by tuxfanx** [comment]
Unfortunately no raw pictures for a test available

**Comment by tuxfanx** [comment]
Thanks for your offer!
The distortion and tca correction are already included in the db. To check your vignetting data, 2-3 images with different apertures would be sufficient. Vignetting correction is often problematic when the aperture is wide open. If you still have the images from the generation of your correction data, you can [upload them here](https://wilson.bronger.org/calibration) instead of new pictures.

**Comment by tuxfanx** [comment]
Thanks for the pictures! Everything looks good.
