### ISSUE TITLE
calibrate.py does not run

### ISSUE THREAD

**Issue by bll123** [lensfun/lensfun#1327]
python3-scipy is installed.
Did scipy change some internal names or something?

bll-g7:bll$ python calibrate.py 
The following packages are missing (Ubuntu packages, names may differ on other systems):
    python3-scipy
Abort.

**Comment by navpp** [comment]
Maybe you installed the scipy-package for python2 and not python3?
However, best is you create an virtual evironment for python3 (this should help: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), activate it and install the libs to it by pip3:
"pip3 install py3exiv2 numpy scipy PyPDF2". This should work on most systems. 

Anyway, I'm not a pro- python nor lensfun user, but the above solution worked for me in an Manjaro/Arch environment. 

Good luck! :)

**Comment by bll123** [comment]
I don't know or use python, so I don't know how to debug its dependency issues.
I did try installing numpy and scipy via pip, but that did not help.

I will try the virtual environment.

**Comment by navpp** [comment]
Could you solve the troubles?

The virtual environment is just that you avoid messing around with dependencies. Sometimes one python package requires a specific version of another package and if you need exactly this package in a different version for the next project, you run into problems. When using virtual envs you can have your project's dependencies divided so that they do not interfere.

If you cannot install the packages with pip/pip3, maybe you can simply try to install the scipy package that comes with your linux distribution? For Ubuntu I guess it is simply "sudo apt-get install python3-scipy". What distro do you use?

**Comment by bll123** [comment]
Haven't had/made time to work on it yet.   Maybe tomorrow or the next day.
Yes, I tried the standard package installs.  
I am using MX Linux (debian 10.7).

**Comment by bll123** [comment]
bll-g7:bll$ python --version
Python 2.7.16

Since I don't use python, I never set the alternatives.
Using 'python3' works.
