### ISSUE TITLE
Add support for "Nikon_AIS_Nikkor_Zoom_43-86mm_f/3.5"

### ISSUE THREAD

**Issue by talmholt** [lensfun/lensfun#1389]
[lensfun-Nikon_AIS_Nikkor_Zoom_43-86mm_f__3.5.zip](https://github.com/lensfun/lensfun/files/6153168/lensfun-Nikon_AIS_Nikkor_Zoom_43-86mm_f__3.5.zip)

**Comment by Sturmflut** [comment]
I am preparing a pull request for this data. Are you sure about the name? It's usually "AI-S" instead of "AI-S", and Nikon seems to call it "Nikon Zoom-NIKKOR Auto 43-86mm F3.5" without the AI-S. There also seems to be a "Nikon Zoom-NIKKOR Auto C 43-86mm F3.5" lens that hat optical coating. Which one is this?

**Comment by talmholt** [comment]
I have a lens that has a serial number between 810000-838000 and per this online resource the lens is actually an AI lens and not a AI-S lens as I initially wrote. 

http://www.photosynthesis.co.nz/nikon/serialno.html

I have the original box for the lens and this is not a C version as also confirmed by the online serial number chart.

**Comment by Sturmflut** [comment]
Thanks for the pointer to the serial number database, I didn't know it yet.

The linked pull request has the changes.
