### ISSUE TITLE
Canon lens not correctly identified

### ISSUE THREAD

**Issue by rebio** [lensfun/lensfun#1412]
For the notes: I'm refering to lensfun used in RawTherapee. It seems that he issue is not with RT, but with lensfun.

There seems to be multiple circumstances when Canon lenses are note correctly identified.

My _Canon EF-S 17-85mm f/4-5.6 IS USM_ says "Canon EF-S 17-85mm f/4-5.6 IS USM **or Tokina Lens**".

This seems to be a problem that pops up every now and then in the RT issue tracker. 
See also:

- https://github.com/Beep6581/RawTherapee/issues/6224
- https://github.com/Beep6581/RawTherapee/issues/5691

Is/should this be fixed by now? Any ideas?

**Comment by gnl21** [comment]
I don't think this is a problem in Lensfun per se, but a problem with how various tools work together to identify lenses. The name of the lens is coming from some exif parsing library (I think RT uses ExifTool?), and that gets passed to lensfun to look for correction data.

As I understand it the LensIDs that the first-party manufacturers use are sometimes also used by third-party manufacturers, so I assume that the exif library is putting "or Tokina Lens" in the name string because it knows about a third-party lens that uses the same ID.

From my point of view it doesn't make sense for lensfun to accept queries for "Canon 17-85 or Tokina Lens", because it doesn't identify a lens that we can give correction data for. It feels like this problem should be solvable, but I'm aware that I haven't really looked into the problem and that those who have found it difficult to deal with.

**Comment by tuxfanx** [comment]
- Problem with Canon EF-S 17-85mm f/4-5.6 IS USM or Tokina Lens depends on exiv2
- Canon EF 70-300mm f/4-5.6 IS II USM is not in lensfuns db
- Canon EF-M 18-55mm, automatic lens detection works with darktable
