### ISSUE TITLE
Calibration data for Tamron E 17-28mm F2.8-2.8

### ISSUE THREAD

**Issue by fheinig** [lensfun/lensfun#1430]
Please add the attached lens data to the lensfun data base.
[Tamron E 17-28mm F2.8-2.8.xml.zip](https://github.com/lensfun/lensfun/files/6604638/Tamron.E.17-28mm.F2.8-2.8.xml.zip)

**Comment by axeleroy** [comment]
Thanks for the profile, I [manually imported it](https://lensfun.github.io/manual/v0.3.2/dbsearch.html) and it works flawlessly.

For those who would like to do the same, just beware that the XML has an invalid `version`, you should edit as follows:

```xml
<lensdatabase version="1">
```

**Comment by axeleroy** [comment]
Oh by the way @fheinig, would you mind if I open a pull request with the profile you created? It might speed up its addition into the lensfun projet.

**Comment by fheinig** [comment]
Dear Axel,

of course, please open the pull request! I'm new to this, could I have done
this myself?
Thanks to the tip regarding the version.

I also uploaded a profile for the recent Tamron 28-200, this will have the
same error (but I integrated it manually into my lensfun database and it
works just as well as the one you tested).
Maybe you will want to include this into the official database as well?


Regards,
Florian

Axel Leroy ***@***.***> schrieb am Do., 15. Juli 2021, 22:35:

**Comment by axeleroy** [comment]
Great, I can do this by tomorrow or next week and I'll make sure to include your other profiles.

Please note that it is not guaranteed to be added to the database as I am not one of the project's maintainers (the people that take care of new additions to the library).

>could I have done this myself?

It requires a little bit of knowledge about git and GitHub's pull request system, but otherwise there are no programming knowledge required. [This article](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) should teach you everything you need.

As for the pull request's content, a good starting point would be to look at [merged pull requests](https://github.com/lensfun/lensfun/pulls?q=is%3Apr+is%3Amerged), especially the "Files changed" tab. 
The latest merged request (#1441) should be a good example, though you don't have to be so thorough in your description (ie. #1434).
