### ISSUE TITLE
XF 10-24mm f/4 R OIS WR

### ISSUE THREAD

**Issue by hyshka** [lensfun/lensfun#1493]
This is an updated version of the existing "XF 10-24mm f/4 R OIS" lens. I am not sure if the specifications are any different but I've been using the old "XF 10-24mm f/4 R OIS" profile for lens correction in Darktable. It would be nice to either get updated data for this new lens or add the new name as a duplicate profile.

I could look into submitting calibration data with the new lens but have not done it before.

**Comment by Sturmflut** [comment]
The "WR" seems to stand for "Weather resistant", which could mean that only things outside of the optical path have changed. But EXIF data seems to be different for this lens, otherwise it would be detected, so there might be a reason for that.

You could try to verify the distortion and TCA parts of the existing profile by taking an image at f/8 that has straight, sharp lines across the picture from the top to the bottom or the left to the right. Then check if the lines get straight and chromatic aberrations disappear if you load it into your RAW converter and select the existing profile.
