### ISSUE TITLE
Is it worth trying to learn the calibration software when I know NOTHING about coding whatsoever?

### ISSUE THREAD

**Issue by Faandyy** [lensfun/lensfun#1937]
Since darktable (for some reason) does not include a module with custom distortion and vignetting correction, I sought this project as a means to help myself. However, I use some certain obscure lenses that (understandably) the volunteers here are not very excited about. I want to create my own profiles then, but I know nothing about coding. Is there something like a for dummies tutorial? Or it is not worth trying at all if I can't code and am generally bad with computer science and logic.

I am fairly proficient with image editing but as soon as the tutorial started mentioning python and dependencies and scripts I instantly had no idea what was being discussed.

**Comment by tuxfanx** [comment]
Coding knowledge is not necessary. Solid knowledge of how to use the operating system is required. In addition, there must be a willingness to invest time and effort in order to be able to carry out the calibration process correctly with the help of the different programs and tutorials. I think only you can answer your question by simply trying it once.
If you don't get it, then upload the required images (#1934) for the calibration, maybe someone will do the calibration. Of course, uploads for lenses that are used a lot in modern times are of greater interest e.g. your 17mm TTArtisan lens ( as I already wrote in #1933).

**Comment by Faandyy** [comment]
> Coding knowledge is not necessary. Solid knowledge of how to use the operating system is required. In addition, there must be a willingness to invest time and effort in order to be able to carry out the calibration process correctly with the help of the different programs and tutorials. I think only you can answer your question by simply trying it once. If you don't get it, then upload the required images (#1934) for the calibration, maybe someone will do the calibration. Of course, uploads for lenses that are used a lot in modern times are of greater interest e.g. your 17mm TTArtisan lens ( as I already wrote in #1933).

Thank you, is there any resource on how exactly I can get the calibration software installed? There is no .exe file in the download, I have no idea what is it that I'm supposed to do.

Don't worry, I still plan to upload some data on the TTArtisan lens, just have not gotten around to bringing it to a place with the specific buildings required for distortion calibration.

**Comment by tuxfanx** [comment]
There is no .exe installation file. calibrate.py or lens_calibrate.py, there are two different phyton scripts you can use, are python scripts which uses various other programs and libaries that must also be installed in addition to Python ([see here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) in section "Create calibration data" [and here](https://wilson.bronger.org/lens_calibration_tutorial/) in section "Preparations"). It may not be easy to set up a windows system accordingly, since phyton scripts where originally created for a Linux OS. I myself have no experience with the setup under windows because I only use a Linux OS. I think it's easier to install a Linux OS and use it for calibration than to bother adjusting a Windows OS.

**Comment by Faandyy** [comment]
> There is no .exe installation file. calibrate.py or lens_calibrate.py, there are two different phyton scripts you can use, are python scripts which uses various other programs and libaries that must also be installed in addition to Python ([see here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) in section "Create calibration data" [and here](https://wilson.bronger.org/lens_calibration_tutorial/) in section "Preparations"). It may not be easy to set up a windows system accordingly, since phyton scripts where originally created for a Linux OS. I myself have no experience with the setup under windows because I only use a Linux OS. I think it's easier to install a Linux OS and use it for calibration than to bother adjusting a Windows OS.

As a windows user, that is a shame. Looks like I won't be able to help afterall.

**Comment by tuxfanx** [comment]
answered-->closed
