### ISSUE TITLE
lensfun uses aps-h instead of aps-c profile for lens correction

### ISSUE THREAD

**Issue by tuxfanx** [lensfun/lensfun#2136]
Here is an example from the slr-canon.xml and for an aps-c raw image that I tried with darktable.
The lens correction for vignetting does not work. But if you move the vignetting data from the aps-c profile to the aps-h profile, then the lens correction takes place.

![Screenshot_20231226_211744](https://github.com/lensfun/lensfun/assets/95431163/2280c1cd-f751-4d52-9eb7-ce334e867ac6)
[20231225__145445.zip](https://github.com/lensfun/lensfun/files/13773688/20231225__145445.zip)

**Comment by gnl21** [comment]
I originally added the data for the APS-C version of this lens and this problem drove me crazy. I tried to fix it in various places but what I think is the correct solution is quite a lot of work and no one else was really affected by the problem.

Lensfun picks the APS-H data on purpose, apparently because it gives a slightly more accurate correction [1]. Unfortunately, it also means that for people like me, who have an APS-C camera but not an APS-H one [2], there's no way to add this data for our lens. One obvious solution to the problem is to stop doing that. I don't know how much this would reduce the accuracy but it would potentially change everyone's old edits (in Darktable, at least) and the lensfun maintainer at the time wasn't keen.

I wrote up what I think is the correct solution in a discussion issue here: https://github.com/lensfun/lensfun/discussions/1765 but it's a bit of work and I don't know if lensfun has enough of a community to get agreement on something like that before starting, so I haven't started.

At this point I'm not sure that changes in the lensfun code will ever be released anyway, so unless there's a pure database fix it may not help anyone anyway. I'd be happy to help finally get this fixed, but there'd need to be a plan to actually get any fix out to people.

Anyway, I hacked it locally, deleted the APS-H data and then lensfun will use my APS-C data correctly.

[1] Apparently the calibration is not so accurate near the edges, so you can a better result by calibrating on a slightly larger sensor where that region is hidden outside the image.

[2] And since APS-H is dead as a format, there's not much hope of this changing.
