### ISSUE TITLE
Separate code base from calibration data.

### ISSUE THREAD

**Issue by payano** [lensfun/lensfun#2140]
I think it would be nice to separate the code base from calibration data and make the calibration data to be a git submodule in the lensfun repo instead. What do you say about that proposal?

**Comment by jonas-ott** [comment]
There is already a (old) discussion about something similar: https://github.com/lensfun/lensfun/issues/1172

A separate repo seems like a god idea. However I'm not sure what's the best way to do this.

- So, it would be necessary to update the submodule, i suppose before every release?
- How do we handle the different database versions? Convert when necessary or a different branch or something else?

Just a submodule would have the advantage of separate issues, commits and pull requests with the downside of additional git commands for cloning lensfun and updating the submodule.

For users it would probably  best to have a `lensfun` and  a `lensfun-data` package with more regular releases, because many don't know about `lensfun-update-data`.
  
I don't know whats best for packaging lensfun.

**Comment by payano** [comment]
Okay, thanks for the update @jonas-ott, maybe it's nice to have in theory but it's harder to implement in practice. I'll close this issue.
