### ISSUE TITLE
Support for Ubiquiti AI 360 Cameras

### ISSUE THREAD

**Issue by zetas** [lensfun/lensfun#2166]
I looked through all the lists I could find of supported cameras and did not see any Ubiquiti Unifi cameras supported. I'm not sure if that's just a lack of interest or if I'm misunderstanding how this project works. Perhaps I need to find what sensor the camera is using? Though not sure how to do that, googling just returns "5MP CMOS" for sensor information. 

Any guidance or help would be great. These cameras are great but they present a fisheye and I'd love to be able to use ffmpeg to dewarp the image for use with homekit or other services using scrypted. 

Thanks again for your time and apologies if this is not the appropriate place for this.

**Comment by CAHEK7** [comment]
I guess the project is mostly focused on photography cameras (slr, mirrorless, phones, etc.) but maintainers know better.
Calibration itself is not a super simple procedure, especially if you want to get some sort of precise calibration and it's hard to cover hundreds or thousands of security cameras for almost no reasons, because most of the time nobody cares about and distortions for security cameras.

As about Ubiquiti cameras - it has pretty good specification with all the parameters like sensor size, field of view, basic lens parameters. For example https://techspecs.ui.com/unifi/cameras-nvrs/uvc-g5-pro has 1/2" sensor and thus crop factor 5.3 and using this crop factor and focal length (4.1) you can do a calibration. Here is an example how to do it https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ (taken from this discussion https://github.com/lensfun/lensfun/discussions/1781)

**Comment by tuxfanx** [comment]
answered --> closed
