### ISSUE TITLE
Inconsistent crop factor on Nikon Z DX lenses

### ISSUE THREAD

**Issue by clawoflight** [lensfun/lensfun#2217]
The Z 50, Z 30 and Z fc mirrorless cameras are all defined with crop factor 1.531:

https://github.com/lensfun/lensfun/blob/d0b3a8c379b1c57d41b028c265829d581c0899e7/data/db/mil-nikon.xml#L207

However, the corresponding lenses are not uniform:

The NIKKOR Z DX 16-50mm f/3.5-6.3 VR is defined with crop factor 1.531:
https://github.com/lensfun/lensfun/blob/d0b3a8c379b1c57d41b028c265829d581c0899e7/data/db/mil-nikon.xml#L910

But the NIKKOR Z DX 50-250mm f/4.5-6.3 VR is defined with crop factor 1.5:
https://github.com/lensfun/lensfun/blob/d0b3a8c379b1c57d41b028c265829d581c0899e7/data/db/mil-nikon.xml#L1267

If I understand correctly how lensfun works, this means that automatic correction with the 50-250mm lens would not be possible due to a mismatch between camera and body, right?

**Comment by tuxfanx** [comment]
@clawoflight
You're right, since the lensfun profile for the NIKKOR Z DX 50-250mm f/4.5-6.3 VR was created with photos from a Z50 camera, the crop factor should have correctly been 1.531.
The autocorrection still works in both, Darktable and RawTherapee.
Since I no longer know which crop factor I was working with in Hugin back then, I don't want to change the crop factor later.
The difference should hardly be visible.
[Here you can find some photos](https://www.dpreview.com/sample-galleries/2079717687/nikon-z50-sample-gallery-dpreview-tv/7633981046) taken with the lens and a Z50. Although they are JPEG images, they contain enough EXIF data to test the automatic recognition.

**Comment by clawoflight** [comment]
Thank you! 
In the mean-time I took some pictures with this camera and lens combination and the autocorrection worked fine.
The pedant in me would still like them to be aligned, but if it's too late for that we can close this issue :)

**Comment by tuxfanx** [comment]
@clawoflight 
You could make the change in your database and test the impact of your pictures. If there are no noticeable differences report it here. Then I could make a change.
