### ISSUE TITLE
Calibration data for Sigma 24mm F3.5 DG DN | Contemporary 021 Lumix vignetting compensation OFF

### ISSUE THREAD

**Issue by Andries-B** [lensfun/lensfun#2287]
Please add the attached lens data to the lensfun data base.

Please note 1: Lumix cameras (both L-mount and MFT) have a menu setting "VIGNETTING.COMP" which impacts the RAW file. RAW files with VIGNETTING.COMP set to ON are different from VIGNETTING.COMP set to OFF. Lumix cameras L-mount and Lumix MFT default to VIGNETTING.COMP set to ON. However, the Lensfun calibration manual instructs to set all settings to OFF, for good reasons. When applying a lens calibration profile that was created from the OFF setting on a RAW file that was shot using the ON profile, to much vignetting correction will be applied, resulting in white corners.
Therefor I'm submitting 2 different profiles for this lens (as 2 separate github issues), where the user can choose (e.g. in darktable) which profile is best for their photo.

https://github.com/user-attachments/files/16820899/lensfun_calibration.tar.gz

**Comment by Andries-B** [comment]
see attached file
[lensfun_calibration.tar.gz](https://github.com/user-attachments/files/16820899/lensfun_calibration.tar.gz)

**Comment by tuxfanx** [comment]
@Andries-B 
I could only import the vignetting profile for switched off raw image correction. Importing both profiles would lead to problems with automatic lens recognition because of the EXIF ​​data.
In addition, Lensfun is intended for correcting pure raw images. Profiles that are intended to be used to correct images that were previously corrected by other software should not be in the official database. Please put it in your own db.

For importing the switched off profile I need some normal raw shots on which I can test the data. 
Pictures of evenly lit, colored surfaces with little structure (e.g. walls, blue sky, garage doors, etc.) are best suited for this. 2-3 images in focus and taken with the wider aperture settings would be sufficient.

**Comment by Andries-B** [comment]
OK, no problem. Here is a newly generated "shipping-package" from lens_calibrate.py. This data is from photos with camera setting Vignette Compensation OFF. Now lens name is exact as exif-data and tca is improved with option "--complex-tca tca". So this complies to lensfun standard of using pure raw images. In the next comment I will attach 2 images for verification.

[lensfun_calibration.tar.gz](https://github.com/user-attachments/files/16825220/lensfun_calibration.tar.gz)

**Comment by Andries-B** [comment]
Trying to upload the images. File size is ~36 MB (zipped ~32 MB). Github allows max. 25 MB. Please advise where I can put or send the images

**Comment by tuxfanx** [comment]
> Trying to upload the images. File size is ~36 MB (zipped ~32 MB). Github allows max. 25 MB. Please advise where I can put or send the images

...use the [lensfun upload](https://wilson.bronger.org/calibration) server and make a link to this issue

**Comment by tuxfanx** [comment]
Thanks for the support!
