### ISSUE TITLE
Calibration data for 27 vintage lenses

### ISSUE THREAD

**Issue by mawob** [lensfun/lensfun#2370]
I have used the script lens_calibrate.py to obtain the distortion (ptlens) and TCA corrections (--complex-tca, poly3) for 27 vintage lenses for full frame sensor (using the Sony A7Rii).

Carl Zeiss Jena Flektogon 20mm f/4
Carl Zeiss Jena Flektogon 35mm f/2.4
Carl Zeiss Jena Pancolar 50mm f/1.8
Carl Zeiss Jena Biotar 58mm f/2
Carl Zeiss Jena Tessar 50mm f/2.8
Carl Zeiss Jena Sonnar 135mm f/3.5
Carl Zeiss Jena Triotar 135mm f/4 (version 2)
Meyer-Optik Görlitz Orestegon 29mm f/2.8
Meyer-Optik Görlitz Lydith 30mm f/3.5
Meyer-Optik Helioplan 40mm f/4.5
Meyer-Optik Görlitz Domiplan 50mm f/2.8
Meyer-Optik Görlitz Oreston 50mm f/1.8
Meyer-Optik Görlitz Orestor 100mm f/2.8
Meyer-Optik Görlitz Orestor 135mm f/2.8
Meyer-Optik Görlitz Orestegor 200mm f/4
Pentacon 50mm f/1.8
Schneider-Kreuznach Retina-Curtagon 28mm f/4
Schneider-Kreuznach Retina-Curtagon 35mm f/2.8
Schneider-Kreuznach Curtagon 35mm f/4
Schneider-Kreuznach Retina-Tele-Arton 85mm f/4
Schneider-Kreuznach Tele-Xenar 90mm f/3.5
Schneider-Kreuznach Retina-Tele-Xenar 135mm f/4
Steinheil München Auto-D-Quinaron 35mm f/2.8
Steinheil München Culminar 85mm f/2.8
Steinheil München Auto-D-Tele-Quinar 135mm f/2.8
Voigtländer Color-Ultron 50mm f/1.8
Beroflex 400mm f/6.3

Details of the procedure and result figures are documented on my blog:
https://markus-wobisch.blogspot.com/2024/11/correcting-lens-distortion-for-vintage.html

The results are stored in a combined .xml file which is linked from my blog (bottom) and attached here as a .zip file
[vintage-glass.zip](https://github.com/user-attachments/files/17852330/vintage-glass.zip)

**Comment by mawob** [comment]
Thank you so much for the quick response. 
Please see my replies below.

> ... The following lenses (crop 1) are probably already included in the lensfun database. However, I am not sure whether they are really the lenses from your database or which profile data are better. Perhaps you can check the lensfun profiles against your pictures and let me know what is best to keep.
> 
> lensfun db / your db
> 
> 1. Carl Zeiss Jena 135mm f/3.5 / Carl Zeiss Jena Sonnar 135mm f/3.5

For (1), I checked that the distortion data is compatible (the numerical values of coefficients a,b,c are somehow different, but the functions agree perfectly) - so you could use either of the two. The previous entry does not have the TCA corrections, so you may use these from my data. But the older entry has vignetting corrections that I don't have, so you could use those. For the model name, you should use my version, to include "Sonnar")

> 2. Carl Zeiss Jena Flektogon 4/20mm / Carl Zeiss Jena Flektogon 20mm f/4
From a comparison, I see that the two distortion functions are pretty compatible.
For TCA, the previous entry has only vr, vb but not the br, bb parameters - so I would suggest to use my results which may be more precise. Also, for the model name, for consistency with the other Zeiss Jena entries, I would suggest my version (with the "f/4" at the end")

> 3. Meyer Optik Görlitz 3.5/30mm / Meyer-Optik Görlitz Lydith 30mm f/3.5
Again: the distortion functions are compatible - but my TCA has all four parameters, so that may be preferable.
And for the name, I would recommend my version with the dash "Meyer-Optik" (that's the official spelling) and the "f/3.5" at the end.

I just see that you have already included almost everything in Github - thank you!!
But just a few comments on that: 
 - for the Meyer-Optik Görlitz 200mm you have the "Meyer-Optik Görlitz" as part of the model (as it should be) while for the others you omitted this. I would suggest to add the "Meyer-Optik Görlitz" to all of their model names.
 - for Schneider: Their real name is "Schneider-Kreuznach" and I would suggest to change this.
 - same for Steinheil: add  "München"

Thank you again!
Markus

**Comment by tuxfanx** [comment]
> * for the Meyer-Optik Görlitz 200mm you have the "Meyer-Optik Görlitz" as part of the model (as it should be) while for the others you omitted this. I would suggest to add the "Meyer-Optik Görlitz" to all of their model names.
> 
removed "Meyer-Optik Görlitz" as part of the model (see reason below)

> * for Schneider: Their real name is "Schneider-Kreuznach" and I would suggest to change this.
> 
changed maker from "Schneider" to "Schneider-Kreuznacht" and removed "Schneider" in model name for all lenses

> * same for Steinheil: add  "München"
>
changed maker from "Steinheil" to "Steinheil München"

**First of all, thank you for the quick answer and your help!**

Should the manufacturer be part of the model string of a lens or not?
This is a frequently discussed point of contention. And if you take a look in the database or at [that List](https://wilson.bronger.org/lensfun_coverage.html), you will find both combinations.
For automatic lenses, it is determined by the EXIF ​​data. But lensfun [allows the addition](https://wilson.bronger.org/lensfun/el_lens.html) of additional words to the model string. For automatic Canon lenses, for historical reasons which I don´t know, we always add "Canon" before the EXIF ​​model string. This is not done for other lenses (e.g. Fujifilm, Nikon, Leica). We calibrators (actually only I) generally stick to the existing practice when we add new lenses so that the confusion does not grow even further.
In order to avoid the display fields for the lenses, in the image editing programs, becoming unnecessarily long and confusing, it is generally an advantage if the manufacturer name does not appear as part of the model name.
For a manual lens for which no exif data is provided, the calibrator is free to decide whether to add the manufacturer name to the model string or not. If the lenses of a manufacturer can be identified by a clear type designation (e.g. for Meyer-Optik, Schneider-Kreuznach and Steinheil München), then, in my opinion, the manufacturer name should not be listed in the model field of the profile in addition to the string in the manufacturer field. However, for lenses from manufacturers that do not allow clear identification via the lens type designation, adding the manufacturer name to the model string is often necessary (e.g. Beroflex).
The Zeiss lens file is currently a complete mess.

I hope you can accept the changes. If there are compelling reasons against it, please let me know.

**Comment by mawob** [comment]
> I hope you can accept the changes. If there are compelling reasons against it, please let me know.

While my initial reasoning was different, I totally see your point - so, yes, I accept.
Thank you again for the great service that you are doing to the community from which I also greatly benefit and, especially, for the super-quick response.
Markus
