### ISSUE TITLE
Please add the Tamron 28-75 mm f/2.8 Di III VXD G2 for Nikon Z 6 III to the Lensfun database. Thank you

### ISSUE THREAD

**Issue by Pepa-D750** [lensfun/lensfun#2388]
It is only in the database for Sony. Thank you.

**Comment by Pepa-D750** [comment]
Hello, I don't understand even after the update the lens is not in the
Lensfun database for Nikon. Can you please explain when it will appear
there when you write that it is closed?
Lensfun - This list was generated on 2024-12-17 from current Lensfun
sources.
Tamron 28-75mm F2.8 Di III VXD G2 (A063S) 1.0 Yes None Yes
So how do I get it into the darktable? Didn't help either:
lensfun-update-data
Sorry, I'm just a user and I'm not a programmer to understand this. What
does : < mount >Sony E</ mount >
        < mount >Nikon Z</ mount > and yet the database is still just ...
(A063S) ?
Thank you for the answer and explanation.

Translated with DeepL.com (free version)

st 25. 12. 2024 v 13:31 odesílatel Joachim Daehnke ***@***.***>
napsal:

**Comment by tuxfanx** [comment]
The data are already included in the lensfun database ([see here in mil-tamron.xml](https://github.com/lensfun/lensfun/blob/662f851f1d958478b710dab146cbc875565f3239/data/db/mil-tamron.xml#L597)).
[This list is updated every night](https://wilson.bronger.org/lensfun_coverage.html).

The installation location of the lensfun database used by darktable depends on the operating system used and the type of installation of darkable.
Which operating system are you using (Linux, Windows, Mac OS)?
How did you install darktable (windows binary, OS package manager, flatpak, snap)?
[Here you can read](https://wilson.bronger.org/lensfun/el_lens.html) something about the profile elements.

**Comment by Pepa-D750** [comment]
Hello, thank you for your reply. As you write that lensfun is updated every
night, how come it is at - https://lensfun.github.io/lenslist/
it says it was generated on 12/17/2024 - (This list was generated on
12/17/2024 from the current Lensfun sources.) and it still only shows the
Sony lens - Tamron 28-75mm F2.8 Di III VXD G2 (A063S) 1.0 Yes None Yes ?
I was using Linux - OS: openSUSE Leap 15.6 x86_64, I installed it from the
community repository because the distro still has darktable 4.8.1 . How
could I update that Lensfun database ?
Thank you very much for the answer and explanation. Have a nice holiday. :-)

Translated with DeepL.com (free version)

st 25. 12. 2024 v 18:09 odesílatel Joachim Daehnke ***@***.***>
napsal:

**Comment by tuxfanx** [comment]
The lists have nothing to do with the current status of the [lensfun database](https://github.com/lensfun/lensfun/tree/master/data/db) on github. These lists are only updated at certain times and they only provide an overview.
Your lens **has already been updated for the mount Nikon Z** and the database on your computer can already be updated with `lensfun-update-data` or manually by copy and paste.

With root rights and `sudo lensfun-update-data`, you are probably updating the lensfun database that was created by Yast (probably under /usr/share/lensfun/version_1). If you run the update as a user without root rights, the current database will be created or updated in your home directory (probably under ~/.local/share/lensfun/updates/version_1/).

However, since you are using darktable from the community repository, it is possible that this darktable version uses another lensfun database that is or should be installed in a different directory. This will probably not be updated by the update-lensfun-data. You then have to either copy and paste the changes yourself or provide darktable with a link to the updated right database.

You should search your system for the existing lensfun databases (e.g. in the terminal with `sudo find / -name lensfun`) and then find out which one is used by your darkable version.

**Comment by Pepa-D750** [comment]
Hello,
thank you so much for your help, I appreciate your work!
Today indeed after the lensfun update the lens already showed up in
darktable in the lens correction. Thanks a lot and have a nice holiday.
Josef Šmolík

st 25. 12. 2024 v 21:15 odesílatel Joachim Daehnke ***@***.***>
napsal:
