### ISSUE TITLE
Fuji X missing compatible mounts

### ISSUE THREAD

**Issue by falket** [lensfun/lensfun#361]
I have noticed i can't select many adapted lenses using a Fuji X-M1 as camera.

There are many adapters for this mirrorless system, now even for Canon EF. Could you please add these mounts as they are as far as i know compatible in mil-fujifilm.xml ?

Thank you in advance.

```
<compat>Minolta MD</compat>
<compat>Pentax K</compat>
<compat>Pentax KAF</compat>
<compat>Pentax KAF2</compat>
<compat>Pentax KAF3</compat>
<compat>Nikon F AI-S</compat>
<compat>Nikon F AF</compat>
<compat>Nikon F</compat>
<compat>Canon EF</compat>
<compat>Canon FD</compat>
<compat>Canon FL</compat>
<compat>Kiev 88</compat>
```

**Comment by junkyardsparkle** [comment]
Compatibility based on adapters isn't currently being added to the shipped database due to the fact that it can end up cluttering the list for a given camera with a *huge* number of lenses. Individual users can add the compats for lenses they want to use this way, either manually or using the [lensfun-add-adapter](http://lensfun.sourceforge.net/manual/v0.3.95/lensfun-add-adapter.html) tool.
