### ISSUE TITLE
Failed to build darktable with latest git/master version of lensfun

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#659]
Hi,

I failed to build darktable with the latest git/master verstion of lensfun.
I've reverted it to 50d406677b80cca413af903c01ac40a4945a2605 and I've no more the problem.

Attached exerpt of the darktable build log

Regards

Jean-Luc

Reported by: north-pole

**Comment by Sturmflut** [comment]
Current darktable master fails to build with current lensfun master, but that seems to be due to darktable having seperate code paths for `LF_VERSION ((0 << 24) | (3 << 16) | (2 << 8)` and `LF_VERSION ((0 << 24) | (3 << 16) | (95 << 8)`. I guess since there hasn't been a new lensfun release for so long, the second code path is not very well tested.

**Comment by Sturmflut** [comment]
Looks like the issue I mentioned is tracked in #508. I guess this issue can be closed.
